### ISSUE TITLE
Gekko Backtest Tool XFFFFFF

### ISSUE THREAD

**Issue by GekkoFreak** [GekkoFreak/GekkoTool#1]
Hello 

I tried to install the GekkoBacktesttool and that worked. 
When I run any command no mather which one ex: perl backtest.pl
[2018-08-04 09:42:37] Collect data from coinmarketcap.com
DBI connect('dbname=history/binance_0.1.db','',...) failed: unable to open database file at backtest.pl line 790 or line 507 

Backtest.pl line 507,790
lines:507: my $dbh = DBI->connect(
line 790:  my $dbh = DBI->connect("dbi:SQLite:dbname=history/$sets[0]_0.1.db", "", "", { RaiseError => 1 },) or die $DBI::errstr;

I installed the binaries and the backtest tool. they are unzipped and in the same file. Also the database file (from XFFFFFF) are in the folder. 

The cpan install went good and no problems. strawberry is installed and in the main gekko folder

What is my problem ? What do i wrong ?

**Comment by GekkoFreak** [comment]
The problem whas the db.


ol v0.7
                                                                                              https://github.com/xFFFFF/Gekko-BacktestTool


[2018-08-04 17:12:21] Collect data from coinmarketcap.com
[2018-08-04 17:12:22] Use TOML files for strategies configuration
[2018-08-04 17:12:22] Save output to csvfile: database.csv
[2018-08-04 17:12:22] Starting Backtest Machine (5 threads)...
============================================================== I N P U T    D A T A ===============================================================
Pairs
-----
binance:USDT:BTC
Total: 1
===================================================================================================================================================
Strategies
----------
MACD CCI RSI
Total: 3

===================================================================================================================================================
Candles
-------
10:73
Total: 1
===================================================================================================================================================
[2018-08-04 17:12:22] 3 backtests remain
============================================================= L A S T    R E S U L T S ============================================================
Pair                                      Strategy       Profit   Profit-market  Trades/day  Win trades  Best win  Worst loss    HODL  Days   Time
----                                      --------       ------   -------------  ----------  ----------  --------  ----------    ----  ----   ----
module.js:549
    throw err;
    ^

Error: Cannot find module 'C:\Users\airdr\Desktop\gekko\Gekkobacktest\gekko'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
USDT-BTC Backtest is failed.
module.js:549
    throw err;
    ^

Error: Cannot find module 'C:\Users\airdr\Desktop\gekko\Gekkobacktest\gekko'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
USDT-BTC Backtest is failed.
module.js:549
    throw err;
    ^

Error: Cannot find module 'C:\Users\airdr\Desktop\gekko\Gekkobacktest\gekko'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
USDT-BTC Backtest is failed.
===================================================================================================================================================

[2018-08-04 17:12:23] 100% complete. Elapsed: 00:00:01, average backtest duration: 00:00


[2018-08-04 17:12:23] Creating ALL RESULTS table (sorted profit/day)...

================================================== A L L     R E S U L T S ===================================================
Curr. Asset Strat Profit Profit-market   Profit/day Trades/day Best win Worst loss Avg.Hodl Avg.price Ov.trades/day Volume/day
----  ----- ----- ------ ------------- ------------ ---------- -------- ---------- -------- --------- -------------  ---------
==============================================================================================================================

[2018-08-04 17:12:23] Creating TOP STRATEGY table...

================================================ T O P    S T R A T E G Y =================================================
Strat Best     %      % profit >  Best  Worst  Sum %  Avg % % Avg win Best  Avg trade Worst Avg trade     Avg       Avg 
           profitable   market    % P/L % P/L profit profit   trades  trade   profit  trade   loss    trades/day  HODL min
----- ---- ----------  ---------- ----- -----  ----- ------ --------- ----- --------- ----- --------- ---------- ---------
==========================================================================================================================

[2018-08-04 17:12:23] Creating TOP DATASET table...

=========================================================== T O P    D A T A S E T ============================================================
Pair  Best     %      % profit >  % Market Best  Worst   Sum %  Avg % % Avg win     Avg        Avg      Price    CMC   Current   Current   Days
           profitable    market    change  % P/L  % P/L profit profit   trades  trades/day  HODL min volatility  Rank marketcap CMC volume
----- ---- ----------  ---------- -------- -----  -----  ----- ------ --------- ---------- --------- ----------  ---- --------- ---------- ----
===============================================================================================================================================


[2018-08-04 17:12:24] All jobs are done. Elapsed time: 2 seconds

**Comment by GekkoFreak** [comment]
issue is fixt 
But I need to import a DB. If I want multiple pairs do i need to import all de db for the pairs ? 
and when I test the strategie I still can change the parameters. So the % in profit can change ? I am correct ?

**Comment by GekkoFreak** [comment]
What in earth am i doing wrong ? 
USDT-BTC Backtest is failed.
